var annotated_dup =
[
    [ "INTELLI", "namespaceINTELLI.html", [
      [ "DatasetTool", "classINTELLI_1_1DatasetTool.html", "classINTELLI_1_1DatasetTool" ],
      [ "MtBucket", "classINTELLI_1_1MtBucket.html", "classINTELLI_1_1MtBucket" ],
      [ "MultiThreadHashTable", "classINTELLI_1_1MultiThreadHashTable.html", "classINTELLI_1_1MultiThreadHashTable" ],
      [ "Tuple", "classINTELLI_1_1Tuple.html", "classINTELLI_1_1Tuple" ],
      [ "RelationCouple", "classINTELLI_1_1RelationCouple.html", "classINTELLI_1_1RelationCouple" ],
      [ "WindowCouple", "classINTELLI_1_1WindowCouple.html", "classINTELLI_1_1WindowCouple" ],
      [ "ConcurrentQWindowCouple", "classINTELLI_1_1ConcurrentQWindowCouple.html", "classINTELLI_1_1ConcurrentQWindowCouple" ],
      [ "Result", "classINTELLI_1_1Result.html", "classINTELLI_1_1Result" ],
      [ "VerifyBench", "classINTELLI_1_1VerifyBench.html", null ],
      [ "AbstractJoinAlgo", "classINTELLI_1_1AbstractJoinAlgo.html", "classINTELLI_1_1AbstractJoinAlgo" ],
      [ "JoinAlgoTable", "classINTELLI_1_1JoinAlgoTable.html", "classINTELLI_1_1JoinAlgoTable" ],
      [ "NestedLoopJoin", "classINTELLI_1_1NestedLoopJoin.html", "classINTELLI_1_1NestedLoopJoin" ],
      [ "NPJ_thread", "classINTELLI_1_1NPJ__thread.html", "classINTELLI_1_1NPJ__thread" ],
      [ "NPJ", "classINTELLI_1_1NPJ.html", "classINTELLI_1_1NPJ" ],
      [ "NPJSingle", "classINTELLI_1_1NPJSingle.html", "classINTELLI_1_1NPJSingle" ],
      [ "AbstractJP", "classINTELLI_1_1AbstractJP.html", "classINTELLI_1_1AbstractJP" ],
      [ "AbstractLazyJP", "classINTELLI_1_1AbstractLazyJP.html", "classINTELLI_1_1AbstractLazyJP" ],
      [ "CellJoinJP", "classINTELLI_1_1CellJoinJP.html", "classINTELLI_1_1CellJoinJP" ],
      [ "HandShakeJP", "classINTELLI_1_1HandShakeJP.html", "classINTELLI_1_1HandShakeJP" ],
      [ "SplitJoinIRJP", "classINTELLI_1_1SplitJoinIRJP.html", "classINTELLI_1_1SplitJoinIRJP" ],
      [ "SplitJoinJP", "classINTELLI_1_1SplitJoinJP.html", "classINTELLI_1_1SplitJoinJP" ],
      [ "AbstractC20Thread", "classINTELLI_1_1AbstractC20Thread.html", "classINTELLI_1_1AbstractC20Thread" ],
      [ "C20Buffer", "classINTELLI_1_1C20Buffer.html", "classINTELLI_1_1C20Buffer" ],
      [ "DupicatedHashTable", "classINTELLI_1_1DupicatedHashTable.html", "classINTELLI_1_1DupicatedHashTable" ],
      [ "MicroDataSet", "classINTELLI_1_1MicroDataSet.html", "classINTELLI_1_1MicroDataSet" ],
      [ "SPSCQueue", "classINTELLI_1_1SPSCQueue.html", "classINTELLI_1_1SPSCQueue" ],
      [ "PerfEntry", "classINTELLI_1_1PerfEntry.html", "classINTELLI_1_1PerfEntry" ],
      [ "PerfTool", "classINTELLI_1_1PerfTool.html", "classINTELLI_1_1PerfTool" ],
      [ "PerfPair", "classINTELLI_1_1PerfPair.html", "classINTELLI_1_1PerfPair" ],
      [ "ThreadPerf", "classINTELLI_1_1ThreadPerf.html", "classINTELLI_1_1ThreadPerf" ],
      [ "UtilityFunctions", "classINTELLI_1_1UtilityFunctions.html", "classINTELLI_1_1UtilityFunctions" ],
      [ "AbstractEagerWS", "classINTELLI_1_1AbstractEagerWS.html", "classINTELLI_1_1AbstractEagerWS" ],
      [ "AbstractLazyWS", "classINTELLI_1_1AbstractLazyWS.html", "classINTELLI_1_1AbstractLazyWS" ],
      [ "AbstractWS", "classINTELLI_1_1AbstractWS.html", "classINTELLI_1_1AbstractWS" ],
      [ "HandShakeWS", "classINTELLI_1_1HandShakeWS.html", "classINTELLI_1_1HandShakeWS" ],
      [ "SplitJoinIRWS", "classINTELLI_1_1SplitJoinIRWS.html", "classINTELLI_1_1SplitJoinIRWS" ],
      [ "SplitJoinWS", "classINTELLI_1_1SplitJoinWS.html", "classINTELLI_1_1SplitJoinWS" ],
      [ "VerifyWS", "classINTELLI_1_1VerifyWS.html", "classINTELLI_1_1VerifyWS" ],
      [ "AbstractJoinMethod", "classINTELLI_1_1AbstractJoinMethod.html", null ],
      [ "CellJoin", "classINTELLI_1_1CellJoin.html", null ],
      [ "HandShakeJoin", "classINTELLI_1_1HandShakeJoin.html", null ],
      [ "OneWayHashJoin", "classINTELLI_1_1OneWayHashJoin.html", null ]
    ] ],
    [ "moodycamel", null, [
      [ "details", null, [
        [ "thread_id_converter", "structmoodycamel_1_1details_1_1thread__id__converter.html", "structmoodycamel_1_1details_1_1thread__id__converter" ],
        [ "identity", "structmoodycamel_1_1details_1_1identity.html", "structmoodycamel_1_1details_1_1identity" ],
        [ "const_numeric_max", "structmoodycamel_1_1details_1_1const__numeric__max.html", null ],
        [ "max_align_t", "unionmoodycamel_1_1details_1_1max__align__t.html", "unionmoodycamel_1_1details_1_1max__align__t" ],
        [ "ConcurrentQueueProducerTypelessBase", "structmoodycamel_1_1details_1_1ConcurrentQueueProducerTypelessBase.html", "structmoodycamel_1_1details_1_1ConcurrentQueueProducerTypelessBase" ],
        [ "_hash_32_or_64", "structmoodycamel_1_1details_1_1__hash__32__or__64.html", null ],
        [ "_hash_32_or_64< 1 >", "structmoodycamel_1_1details_1_1__hash__32__or__64_3_011_01_4.html", null ],
        [ "hash_32_or_64", "structmoodycamel_1_1details_1_1hash__32__or__64.html", null ],
        [ "nomove_if", "structmoodycamel_1_1details_1_1nomove__if.html", null ],
        [ "nomove_if< false >", "structmoodycamel_1_1details_1_1nomove__if_3_01false_01_4.html", null ],
        [ "is_trivially_destructible", "structmoodycamel_1_1details_1_1is__trivially__destructible.html", null ],
        [ "static_is_lock_free_num", "structmoodycamel_1_1details_1_1static__is__lock__free__num.html", null ],
        [ "static_is_lock_free_num< signed char >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01signed_01char_01_4.html", null ],
        [ "static_is_lock_free_num< short >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01short_01_4.html", null ],
        [ "static_is_lock_free_num< int >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01int_01_4.html", null ],
        [ "static_is_lock_free_num< long >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01_4.html", null ],
        [ "static_is_lock_free_num< long long >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01long_01_4.html", null ],
        [ "static_is_lock_free", "structmoodycamel_1_1details_1_1static__is__lock__free.html", null ],
        [ "static_is_lock_free< bool >", "structmoodycamel_1_1details_1_1static__is__lock__free_3_01bool_01_4.html", null ],
        [ "static_is_lock_free< U * >", "structmoodycamel_1_1details_1_1static__is__lock__free_3_01U_01_5_01_4.html", null ]
      ] ],
      [ "ConcurrentQueueDefaultTraits", "structmoodycamel_1_1ConcurrentQueueDefaultTraits.html", "structmoodycamel_1_1ConcurrentQueueDefaultTraits" ],
      [ "ConcurrentQueue", "classmoodycamel_1_1ConcurrentQueue.html", "classmoodycamel_1_1ConcurrentQueue" ],
      [ "BlockingConcurrentQueue", "classmoodycamel_1_1BlockingConcurrentQueue.html", null ],
      [ "ProducerToken", "structmoodycamel_1_1ProducerToken.html", "structmoodycamel_1_1ProducerToken" ],
      [ "ConsumerToken", "structmoodycamel_1_1ConsumerToken.html", "structmoodycamel_1_1ConsumerToken" ]
    ] ],
    [ "std", null, [
      [ "SafeQueue", "classstd_1_1SafeQueue.html", "classstd_1_1SafeQueue" ]
    ] ],
    [ "_hash_32_or_64<(size > 4)>", "class__hash__32__or__64_3_07size_01_4_014_08_4.html", null ]
];