FROM ubuntu:22.04
ENV USER=OoOJoin
ENV PASSWD=OoOJoin
ENV WORKDIR=projects


# 安装开发环境必要的包/Install the requied deb packs
RUN apt-get update &&\
  apt-get install -y \
      gcc \
      g++ \
      gdb \
      clang \
      make \
      ninja-build \
      cmake \
      autoconf \
      automake \
      rsync \
      tar \
      git \
      liblog4cxx-dev \
      net-tools \
      openssh-server \
      nano \
      liblog4cxx-dev \
      libboost-dev \
      libboost-all-dev \
      gdbserver \
      python3 \
      python3-pip
RUN apt-get clean
RUN apt-get install -y sudo
RUN pip3 install torch==1.13.0 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
# 添加用户并配置密码/Add user and config passwd
RUN useradd -m ${USER} && yes ${PASSWD} | passwd ${USER}

# 赋予sudo权限并允许无密码sudo/ Enable a sudo and allow passwd-free use
RUN echo ${USER}' ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN chmod 644 /etc/sudoers
RUN echo 'Port 22' >> /etc/ssh/sshd_config
RUN echo 'service ssh start' >> /etc/init.d/docker_ssh
RUN chmod 775 /etc/init.d/docker_ssh
RUN update-rc.d docker_ssh defaults 999
#RUN passwd root ${PASSWD}

#CMD ["/usr/sbin/sshd", "-D"]

USER ${USER}
RUN mkdir -p /home/${USER}/${WORKDIR}/
RUN sudo echo 'sudo service ssh restart' >> ~/.bashrc
#ENV LC_ALL C.UTF-8
